### ISSUE TITLE
Suggestions for condition list

### ISSUE THREAD

**Issue by jconcilio** [ahcis-rds/study_finder#13]
Not urgent, but a couple conditions we have studies for that I noticed, that would be nice to include in the condition list:

Guillain Barre syndrome (GBS)
Chronic immune demyelinating polyneuropathy (CIDP)
Sjogren's syndrome
Inflammatory myopathy
Inclusion body myositis
Dermatomyositis
Polymyositis
Lambert-Eaton myasthenic syndrome (LEMS)
Congenital myasthenic syndromes
Myotonic dystrophy
Limb girdle muscular dystrophy (LGMD)
Pompe disease

Not a rush, but we definitely refer to them a lot!

**Comment by blackjk3** [comment]
@jconcilio the condition list is generated from the trials that are pulled down from ct.gov.  Are you saying that those conditions are tagged in the trials that you are pulling down from ct.gov but not showing up in StudyFinder?

**Comment by jconcilio** [comment]
Well, I had previously thought so, but then I realized that in at least one of the cases, it's listed, but not listed as a "condition." (It's just in the text, and there are no conditions listed specifically.) It makes sense that it'd pull by conditions, though. Let me look into it a little more and see if I can come up with some specific ones to test, and then see what happens. I hadn't thought about that!

**Comment by blackjk3** [comment]
Great! Keep me posted. I'll keep the issue open and if we don't find any specific test cases we can close it at that point.

**Comment by jconcilio** [comment]
Yeah, you can close this - it's the case that while conditions were listed in the description, they weren't included AS conditions in ClinicalTrials.gov, and I'm working with the study coordinators on improving that on their end.
