### ISSUE TITLE
Clinicaltrials.gov download not working

### ISSUE THREAD

**Issue by adecab** [ahcis-rds/study_finder#155]
The load process in ctgov.rb not longer works.

     url = "https://clinicaltrials.gov/search?locn=#{URI::encode(@system_info.search_term)}&studyxml=true"

This will return search_result.zip file with a html page inside instead of the xml files.

**Comment by machinehum** [comment]
@adecab Thank you for the report. Looks like clinicaltrials.gov made a slight change to the URL for downloading the zipped XML files for a search. This should be fixed by https://github.com/ahcis-rds/study_finder/commit/18c09d2d5405e825605a183e3e9ae60a721e9451
