### ISSUE TITLE
selecting both age checkboxes returns 0 results

### ISSUE THREAD

**Issue by jrobertson3** [ahcis-rds/study_finder#32]
On either the home page or the 'Refine your search' page, checking both age boxes (Children and Adults) returns no results.  If I select one or the other, the result is correct.

The problem happens if I check both at the same time, or if I have already searched with one checkbox selected and then select the other checkbox and search again.
[StudyFinder Search Issue 042417.docx](https://github.com/ahcis-rds/study_finder/files/952267/StudyFinder.Search.Issue.042417.docx)

**Comment by johnsja** [comment]
@jrobertson3 is this still an issue? I've tested locally and cannot reproduce. I also peeked at the production penn state studyfinder and all appears to be working as expected.
